### ISSUE TITLE
Expired certificate on https://indigenous.abode.pub/ 

### ISSUE THREAD

**Issue by smaffulli** [swentel/indigenous-ios#251]
Authentication on iOS fails because the app tries to connect to https://indigenous.abode.pub/ where the Letsencrypt certificate expired on 8/19/2020, 1:51:32 AM (Pacific Standard Time)

**Comment by swentel** [comment]
Moving to the right repo. I don't control that domain. I need to get a basic new version out removing these old references.

**Comment by swentel** [comment]
same as https://github.com/swentel/indigenous-ios/issues/250

**Comment by Cambridgeport90** [comment]
Keep us updated! Can’t wait!

**Comment by EdwardHinkle** [comment]
@Cambridgeport90 This should be fixed now
